/**
 * Enrichment Module
 *
 * Unified exports for all enrichment functionality including:
 * - API clients (SimilarWeb, BuiltWith, Yahoo Finance, WebSearch)
 * - Data transformers
 * - Orchestrator for coordinated enrichment
 *
 * @example
 * ```typescript
 * import { enrichmentOrchestrator, ENRICHMENT_LEVELS } from '@/services/enrichment';
 *
 * // Full enrichment with progress
 * const result = await enrichmentOrchestrator.enrich('example.com', 'deep', {
 *   companyName: 'Example Inc',
 *   onProgress: (progress) => console.log(progress)
 * });
 * ```
 *
 * @module enrichment
 */

// =============================================================================
// Clients - Direct API access
// =============================================================================

export {
  // SimilarWeb
  SimilarWebClient,
  similarWebClient,
  SimilarWebError,
  SimilarWebRateLimitError,
  SimilarWebNotFoundError,
  type SimilarWebTrafficData,
  type SimilarWebTrafficSources,
  type SimilarWebCountry,
  type SimilarWebGeography,
  type SimilarWebDemographics,
  type SimilarWebKeyword,
  type SimilarWebCompetitor,
  type SimilarWebReferral,
  type SimilarWebPage,
  type SimilarWebAudienceInterest,
  type SimilarWebRank,
  type SimilarWebFullData,
  // BuiltWith
  BuiltWithClient,
  builtWithClient,
  type BuiltWithTechnology,
  type BuiltWithTechStack,
  type BuiltWithRelationships,
  type BuiltWithRecommendations,
  type BuiltWithFinancials,
  type BuiltWithSocial,
  type BuiltWithTrust,
  type BuiltWithFullData,
  // Yahoo Finance
  YahooFinanceClient,
  yahooFinanceClient,
  formatFinancialNumber as formatYahooFinancialNumber,
  formatPercentage as formatYahooPercentage,
  isPublicCompany,
  type YahooQuoteSummary,
  type YahooIncomeStatement,
  type YahooBalanceSheet,
  type YahooCashFlow,
  type YahooQuarterlyResult,
  type YahooStockInfo,
  type YahooAnalystRating,
  type YahooRecommendations,
  type YahooHolder,
  type YahooNews,
  type YahooPriceHistory,
  type YahooFinancials3Year,
  type YahooFinanceFullData,
  // WebSearch
  WebSearchProxy,
  webSearchProxy,
  buildHiringSearchQueries,
  buildExecutiveSearchQueries,
  buildInvestorSearchQueries,
  buildStrategicSearchQueries,
  buildEdgarSearchUrl,
  getCareersPagesUrls,
  getEdgarFilingsUrls,
  parseHiringResults,
  parseExecutiveResults,
  parseInvestorResults,
  parseStrategicResults,
  scoreJobRelevance,
  calculateHiringSignalStrength,
  mapQuoteToAlgoliaValue,
  extractTopicTags,
  scoreQuoteRelevance,
  categorizeRiskFactor,
  identifyTriggerEventType,
  scoreTriggerRelevance,
  ALGOLIA_RELEVANT_TOPICS,
  type HiringJob,
  type HiringSignal,
  type ExecutiveQuote,
  type ExecutiveData,
  type SecFiling,
  type RiskFactor,
  type EarningsHighlight,
  type InvestorData,
  type StrategicTrigger,
  type StrategicData,
  type WebSearchFullData,
  type SearchResult,
  type SearchExecutor,
} from './clients';

// =============================================================================
// Transformers - Data transformation utilities
// =============================================================================

export {
  // Traffic
  transformTrafficData,
  transformTrafficSources,
  getDominantTrafficSource,
  getOrganicVsPaidRatio,
  transformGeography,
  getPrimaryCountry,
  isUSCentric,
  getRegionalBreakdown,
  estimateDeviceDistribution,
  calculateTrafficTrend,
  classifyTrafficTrend,
  getTrafficTier,
  getTrafficTierScore,
  getTrafficDescription,
  calculateEngagementScore,
  getEngagementLevel,
  estimateSearchQueryVolume,
  classifySearchOpportunity,
  formatMonthlyVisits,
  formatDuration,
  formatPercentage,
  type TrafficTier,
  // TechStack
  transformTechStackData,
  transformTechStackFromBuiltWith,
  transformTechnologies,
  extractTagManagers,
  detectPartnerTech,
  hasPartnerTech,
  PARTNER_TECH_PATTERNS,
  detectSearchProvider,
  usesAlgolia,
  usesCompetitorSearch,
  SEARCH_PROVIDERS,
  hasWeakSearchPlatform,
  getWeakSearchPlatforms,
  WEAK_SEARCH_PLATFORMS,
  calculateTechComplexity,
  getTechSophisticationLevel,
  calculateDisplacementOpportunity,
  getDisplacementClassification,
  getTechByCategory,
  hasTechnology,
  formatKeyTechnologies,
  getTechCount,
  // Competitors
  transformCompetitorData,
  transformCompetitor,
  detectSearchProviderFromTechStack,
  extractCompanyName,
  determineMarketPosition,
  getMarketCompetitivenessScore,
  generateCompetitiveLandscape,
  countSearchProviders,
  countAlgoliaCompetitors,
  getAlgoliaCompetitors,
  getAlgoliaAdoptionRate,
  getCompetitivePressure,
  getCompetitorDomainsForEnrichment,
  filterByMinSimilarity,
  getTopCompetitors,
  calculateDisplacementUrgency,
  generateDisplacementNarrative,
  formatCompetitor,
  formatCompetitorList,
  getSearchProviderBreakdown,
  // Financials
  transformFinancialData,
  transformRevenueMetrics,
  transformNetIncomeMetrics,
  transformEbitdaMetrics,
  calculateEbitdaMargin,
  determineMarginZone,
  estimateEcommercePercentage,
  estimateEcommerceRevenue,
  calculateRoiEstimate,
  getFinancialHealthScore,
  getFinancialHealthLevel,
  calculateRevenueCAGR,
  getRevenueTrend,
  formatFinancialNumber,
  formatGrowthPercentage,
  formatRoiEstimate,
  transformStockInfo,
  transformIncomeStatement,
  transformBalanceSheet,
  transformHistoricalFinancials,
  transformAnalystRatings,
  calculateGrowthRates,
  calculateMargins,
  transformFullFinancialData,
  estimatePrivateCompanyFinancials,
  getPrivateCompanyEstimateConfidence,
  type ExtendedFinancialData,
  // Hiring
  transformHiringData,
  transformJob,
  getHiringSignalScore,
  getHiringSignalLevel,
  isHiringForSearch,
  isHiringForDiscovery,
  getSearchRelatedJobs,
  getExecutiveHires,
  getDirectorHires,
  isBuildingTeam,
  getDepartmentBreakdown,
  getPrimaryHiringDepartment,
  inferTechStackFromHiring,
  formatHiringSignal,
  formatTierBreakdown,
  getHiringSummary,
  transformHiringJobToKeyRole,
  calculateEnrichedTierBreakdown,
  extractTechSignals,
  determineGrowthIndicators,
  transformToEnrichedHiringData,
  getHiringInsights,
  type EnrichedHiringData,
  // Executive
  transformExecutiveData,
  transformQuote,
  transformTheme,
  calculateQuoteRelevance,
  getExecutiveSignalScore,
  getExecutiveSignalLevel,
  extractStrategicPriorities,
  mapTextToAlgoliaValue,
  getCLevelQuotes,
  hasCEOQuotes,
  getMostSeniorSpeaker,
  getMostFrequentTheme,
  getSearchRelatedThemes,
  getCXRelatedThemes,
  categorizeQuotes,
  getQuotesByValue,
  formatQuoteForDisplay,
  getExecutiveSummary,
  getBestQuote,
  scoreQuoteRelevanceLevel,
  mapQuoteToAlgoliaValueProp,
  extractSpeakingPhrases,
  generateAlgoliaAngle,
  transformToExecutiveInsights,
  getExecutiveActionableInsights,
  ALGOLIA_VALUE_PROPS,
  type ExecutiveInsights,
  // Investor
  transformInvestorData,
  transformSecFiling,
  transformEarningsHighlight,
  transformRiskFactor,
  parseQuarterToDate,
  getInvestorSignalScore,
  getInvestorSignalLevel,
  extractRelevantRiskFactors,
  getRiskFactorsByRelevance,
  categorizeRiskFactors,
  hasTechnologyRisks,
  getMostRecent10K,
  getMostRecent10Q,
  getFilingsByType,
  hasRecentFilings,
  getMostRecentEarnings,
  getEarningsWithTopic,
  getAllEarningsKeyPoints,
  earningsMentionDigitalTransformation,
  formatSecFiling,
  formatRiskFactor as formatInvestorRiskFactor,
  getInvestorSummary,
  getMostActionableInsight,
  transformSecFilingEnhanced,
  transformRiskFactorEnhanced,
  extractDigitalMentions,
  extractSearchMentions,
  determineDigitalTransformationStage,
  extractGrowthDrivers,
  extractHeadwinds,
  transformToInvestorIntelligence,
  getInvestorActionableInsights,
  RISK_MITIGATIONS,
  type InvestorIntelligence,
} from './transformers';

// =============================================================================
// Orchestrator - Coordinated enrichment
// =============================================================================

export {
  EnrichmentOrchestrator,
  enrichmentOrchestrator,
  ENRICHMENT_LEVELS,
  STAGE_NAMES,
  type EnrichmentLevel,
  type EnrichmentLevelConfig,
  type EnrichmentStage,
  type EnrichmentProgress,
  type EnrichmentError,
  type EnrichmentResult,
  type EnrichOptions,
  type BatchEnrichOptions,
  type ProgressCallback,
} from './orchestrator';

// =============================================================================
// Default Export - Orchestrator for easy use
// =============================================================================

export { enrichmentOrchestrator as default } from './orchestrator';

// =============================================================================
// Re-export types from main types file for convenience
// =============================================================================

export type {
  TrafficData,
  TrafficSource,
  CountryTraffic,
  TechStackData,
  Technology,
  FinancialData,
  FinancialMetric,
  RoiEstimate,
  CompetitorData,
  Competitor,
  HiringData,
  Job,
} from '@/types';
